# Generated by Django 4.2.3 on 2025-10-18 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(help_text='Name of the organization', max_length=255, verbose_name='Organization Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the organization was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the organization was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the organization is active', verbose_name='Is Active')),
                ('manager', models.ForeignKey(help_text='Manager responsible for this organization', limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['org_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('org_name', 'manager')},
        ),
    ]
