# Generated by Django 4.2.3 on 2025-10-18 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("manager_dashboard", "0004_membertimezones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "week_start_date",
                    models.DateField(
                        help_text="Monday of the week this schedule covers", verbose_name="Week Start Date"
                    ),
                ),
                (
                    "week_end_date",
                    models.DateField(
                        help_text="Sunday of the week this schedule covers", verbose_name="Week End Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        help_text="Current status of the schedule",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the schedule was created", verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the schedule was last updated", verbose_name="Updated At"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team this schedule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="manager_dashboard.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "ordering": ["-week_start_date"],
                "unique_together": {("team", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="Timeslot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="When this timeslot starts", verbose_name="Start DateTime"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="When this timeslot ends", verbose_name="End DateTime"),
                ),
                (
                    "is_break",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a break period (no assignment needed)",
                        verbose_name="Is Break",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the timeslot was created", verbose_name="Created At"
                    ),
                ),
                (
                    "assigned_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Member assigned to this timeslot",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_timeslots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        help_text="Schedule this timeslot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslots",
                        to="assign_task.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeslot",
                "verbose_name_plural": "Timeslots",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="TeamScheduleConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "timeslot_duration_hours",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Duration of each timeslot in hours (max 8)",
                        verbose_name="Timeslot Duration (hours)",
                    ),
                ),
                (
                    "min_break_hours",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Minimum break between shifts in hours",
                        verbose_name="Minimum Break (hours)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the configuration was created", verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the configuration was last updated", verbose_name="Updated At"
                    ),
                ),
                (
                    "team",
                    models.OneToOneField(
                        help_text="Team this configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_config",
                        to="manager_dashboard.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Schedule Configuration",
                "verbose_name_plural": "Team Schedule Configurations",
            },
        ),
        migrations.CreateModel(
            name="ScheduleValidation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the schedule passes all validation rules",
                        verbose_name="Is Valid",
                    ),
                ),
                (
                    "has_sufficient_members",
                    models.BooleanField(
                        default=False,
                        help_text="Whether there are enough members to cover all timeslots",
                        verbose_name="Has Sufficient Members",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        default=list, help_text="List of validation error messages", verbose_name="Validation Errors"
                    ),
                ),
                (
                    "validation_warnings",
                    models.JSONField(
                        default=list,
                        help_text="List of validation warning messages",
                        verbose_name="Validation Warnings",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the validation was performed", verbose_name="Created At"
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        help_text="Schedule this validation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="assign_task.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Validation",
                "verbose_name_plural": "Schedule Validations",
            },
        ),
    ]
