# Generated by Django 4.2.3 on 2025-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assign_task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminScheduleConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "max_daily_hours",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Maximum hours an employee can work per day",
                        verbose_name="Max Daily Hours",
                    ),
                ),
                (
                    "max_weekly_hours",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Maximum hours an employee can work per week",
                        verbose_name="Max Weekly Hours",
                    ),
                ),
                (
                    "max_timeslot_duration",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Maximum duration of a single timeslot in hours",
                        verbose_name="Max Timeslot Duration",
                    ),
                ),
                (
                    "min_team_size_for_scheduling",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum team size required for automatic scheduling",
                        verbose_name="Minimum Team Size",
                    ),
                ),
                (
                    "default_timeslot_duration",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Default timeslot duration for new teams",
                        verbose_name="Default Timeslot Duration",
                    ),
                ),
                (
                    "default_min_break_hours",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Default minimum break between shifts for new teams",
                        verbose_name="Default Minimum Break",
                    ),
                ),
                (
                    "scheduling_algorithm",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round Robin"),
                            ("balanced", "Balanced Load"),
                            ("preference_based", "Preference Based"),
                        ],
                        default="round_robin",
                        help_text="Algorithm used for automatic scheduling",
                        max_length=20,
                        verbose_name="Scheduling Algorithm",
                    ),
                ),
                (
                    "auto_publish_threshold",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Percentage of teams that must be valid before auto-publishing (0-100)",
                        verbose_name="Auto-Publish Threshold",
                    ),
                ),
                (
                    "organization_timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Default timezone for the organization",
                        max_length=100,
                        verbose_name="Organization Timezone",
                    ),
                ),
                (
                    "business_days",
                    models.JSONField(
                        default=list,
                        help_text="Days of the week when scheduling is active (0=Monday, 6=Sunday)",
                        verbose_name="Business Days",
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notifications for schedule changes",
                        verbose_name="Enable Email Notifications",
                    ),
                ),
                (
                    "enable_sms_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Send SMS notifications for urgent changes",
                        verbose_name="Enable SMS Notifications",
                    ),
                ),
                (
                    "notification_advance_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="How many days in advance to notify about schedules",
                        verbose_name="Notification Advance Days",
                    ),
                ),
                (
                    "min_rest_hours",
                    models.PositiveIntegerField(
                        default=12, help_text="Minimum rest period between shifts", verbose_name="Minimum Rest Hours"
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum consecutive days an employee can work",
                        verbose_name="Max Consecutive Days",
                    ),
                ),
                (
                    "overtime_threshold_hours",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Hours after which overtime rules apply",
                        verbose_name="Overtime Threshold",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the scheduling system is active", verbose_name="Is Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the configuration was created", verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the configuration was last updated", verbose_name="Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Schedule Configuration",
                "verbose_name_plural": "Admin Schedule Configurations",
            },
        ),
    ]
