# Generated by Django 4.2.3 on 2025-10-18 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assign_task", "0002_adminscheduleconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminScheduleConfig",
        ),
    ]
