# Generated by Django 4.2.3 on 2025-10-18 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assign_task", "0003_remove_admin_schedule_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[("published", "Published"), ("archived", "Archived")],
                default="published",
                help_text="Current status of the schedule",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="SwapRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("processed", "Processed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Current status of the swap request",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the swap was requested", verbose_name="Request Date"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(help_text="24 hours before the first slot starts", verbose_name="Deadline"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the swap was processed", null=True, verbose_name="Processed At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection if applicable", verbose_name="Rejection Reason"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the swap request was created", verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the swap request was last updated", verbose_name="Updated At"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="Member requesting the swap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester_slot",
                    models.ForeignKey(
                        help_text="Slot the requester wants to give up",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_as_requester",
                        to="assign_task.timeslot",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        help_text="Member being asked to swap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responder_slot",
                    models.ForeignKey(
                        help_text="Slot the responder is being asked to give up",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_as_responder",
                        to="assign_task.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Swap Request",
                "verbose_name_plural": "Swap Requests",
                "ordering": ["-created_at"],
                "unique_together": {("requester_slot", "responder_slot")},
            },
        ),
    ]
