# Generated by Django 4.2.7 on 2025-01-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Name of the team', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the team was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the team was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the team is active')),
                ('organization', models.ForeignKey(help_text='Organization this team belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['team_name'],
                'unique_together': {('team_name', 'organization')},
            },
        ),
    ]
