# Generated by Django 4.2.7 on 2025-01-18 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('manager_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the person being invited', max_length=254, verbose_name='Email Address')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for the invitation', unique=True, verbose_name='Invitation Token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the invitation', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was created', verbose_name='Created At')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires', verbose_name='Expires At')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True, verbose_name='Accepted At')),
                ('invited_by', models.ForeignKey(help_text='Manager who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization the person is being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'organization')},
            },
        ),
    ]
