# Generated by Django 4.2.7 on 2025-01-18 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('manager_dashboard', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the member joined the team', verbose_name='Joined At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is active', verbose_name='Is Active')),
                ('member', models.ForeignKey(help_text='User who is a member of the team', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='Team the member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='manager_dashboard.team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-joined_at'],
                'unique_together': {('team', 'member')},
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(help_text='Team the person is being invited to join', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='manager_dashboard.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(help_text='Organization the person is being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='authentication.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'team')},
        ),
    ]
