# Generated by Django 4.2.3 on 2025-10-18 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manager_dashboard", "0003_invitation_team_and_team_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberTimezones",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "timezone",
                    models.CharField(
                        help_text="User's preferred timezone (e.g., 'America/New_York', 'Europe/London')",
                        max_length=100,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the timezone preference was set", verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the timezone preference was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User whose timezone preference this is",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timezone_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Timezone",
                "verbose_name_plural": "Member Timezones",
                "ordering": ["-created_at"],
            },
        ),
    ]
